// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * uic_Status;
lv_obj_t * uic_SystemTab;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_SystemTab = NULL;
lv_obj_t * ui_StatusTab = NULL;
lv_obj_t * ui_Status = NULL;
lv_obj_t * ui_Wifi = NULL;
lv_obj_t * ui_WifiStatus = NULL;
lv_obj_t * ui_SSID = NULL;
lv_obj_t * ui_IpAddress = NULL;
lv_obj_t * ui_WebPage = NULL;
lv_obj_t * ui_System = NULL;
lv_obj_t * ui_CpuTemp = NULL;
lv_obj_t * ui_CpuLoad = NULL;
lv_obj_t * ui_RamUsage = NULL;
lv_obj_t * ui_UpTime = NULL;
lv_obj_t * ui_SensorsTab = NULL;
lv_obj_t * ui_SensorsData = NULL;
lv_obj_t * ui_SensorsChart = NULL;
lv_obj_t * ui_SensorsChart_Xaxis = NULL;
lv_obj_t * ui_SensorsChart_Yaxis1 = NULL;
lv_obj_t * ui_SensorsChart_Yaxis2 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SystemTab = lv_tabview_create(ui_Screen1);
    lv_tabview_set_tab_bar_size(ui_SystemTab, 50);
    lv_obj_set_width(ui_SystemTab, 480);
    lv_obj_set_height(ui_SystemTab, 320);
    lv_obj_set_align(ui_SystemTab, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SystemTab, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SystemTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_remove_flag(ui_SystemTab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StatusTab = lv_tabview_add_tab(ui_SystemTab, "Status");
    lv_obj_set_flex_flow(ui_StatusTab, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_StatusTab, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Status = lv_obj_create(ui_StatusTab);
    lv_obj_remove_style_all(ui_Status);
    lv_obj_set_width(ui_Status, 480);
    lv_obj_set_height(ui_Status, 261);
    lv_obj_set_x(ui_Status, 2);
    lv_obj_set_y(ui_Status, -23);
    lv_obj_set_align(ui_Status, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Status, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Status, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_Status, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi = lv_obj_create(ui_Status);
    lv_obj_remove_style_all(ui_Wifi);
    lv_obj_set_width(ui_Wifi, 298);
    lv_obj_set_height(ui_Wifi, 103);
    lv_obj_set_x(ui_Wifi, -24);
    lv_obj_set_y(ui_Wifi, -130);
    lv_obj_set_align(ui_Wifi, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Wifi, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Wifi, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Wifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifi, lv_color_hex(0x2F6CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifi, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Wifi, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatus = lv_label_create(ui_Wifi);
    lv_obj_set_x(ui_WifiStatus, -64);
    lv_obj_set_y(ui_WifiStatus, -50);
    lv_obj_set_align(ui_WifiStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiStatus, "WiFi: Connected");

    ui_SSID = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_SSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSID, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_y(ui_SSID, -1);
    lv_obj_set_x(ui_SSID, lv_pct(61));
    lv_obj_set_align(ui_SSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SSID, "SSID: MyNetwork");

    ui_IpAddress = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_IpAddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IpAddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IpAddress, 0);
    lv_obj_set_y(ui_IpAddress, 14);
    lv_obj_set_align(ui_IpAddress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IpAddress, "IP: 192.168.1.42");

    ui_WebPage = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_WebPage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WebPage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WebPage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WebPage, "URL: http://device.local");

    ui_System = lv_obj_create(ui_Status);
    lv_obj_remove_style_all(ui_System);
    lv_obj_set_width(ui_System, 299);
    lv_obj_set_height(ui_System, 101);
    lv_obj_set_x(ui_System, -24);
    lv_obj_set_y(ui_System, -130);
    lv_obj_set_align(ui_System, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_System, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_System, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_System, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_System, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_System, lv_color_hex(0x2F6CFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_System, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_System, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_System, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CpuTemp = lv_label_create(ui_System);
    lv_obj_set_x(ui_CpuTemp, -64);
    lv_obj_set_y(ui_CpuTemp, -50);
    lv_obj_set_align(ui_CpuTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CpuTemp, "CPU Temp: 45°C");

    ui_CpuLoad = lv_label_create(ui_System);
    lv_obj_set_width(ui_CpuLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CpuLoad, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_y(ui_CpuLoad, -1);
    lv_obj_set_x(ui_CpuLoad, lv_pct(61));
    lv_obj_set_align(ui_CpuLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CpuLoad, "CPU Load: 12%");

    ui_RamUsage = lv_label_create(ui_System);
    lv_obj_set_width(ui_RamUsage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RamUsage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RamUsage, 0);
    lv_obj_set_y(ui_RamUsage, 14);
    lv_obj_set_align(ui_RamUsage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RamUsage, "RAM: 120MB/512MB");

    ui_UpTime = lv_label_create(ui_System);
    lv_obj_set_width(ui_UpTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UpTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpTime, "Uptime: 01:23:45");

    ui_SensorsTab = lv_tabview_add_tab(ui_SystemTab, "Sensors");
    lv_obj_set_flex_flow(ui_SensorsTab, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SensorsTab, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_SensorsData = lv_obj_create(ui_SensorsTab);
    lv_obj_remove_style_all(ui_SensorsData);
    lv_obj_set_width(ui_SensorsData, 361);
    lv_obj_set_height(ui_SensorsData, 163);
    lv_obj_set_x(ui_SensorsData, -2);
    lv_obj_set_y(ui_SensorsData, -20);
    lv_obj_set_align(ui_SensorsData, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SensorsData, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SensorsData, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SensorsData, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SensorsChart = lv_chart_create(ui_SensorsData);
    lv_obj_set_width(ui_SensorsChart, 269);
    lv_obj_set_height(ui_SensorsChart, 128);
    lv_obj_set_align(ui_SensorsChart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SensorsChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_SensorsChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_SensorsChart,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_SensorsChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_SensorsChart, LV_CHART_TYPE_LINE);
    lv_obj_set_style_bg_color(ui_SensorsChart, lv_color_hex(0x0015D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SensorsChart, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SensorsChart_Xaxis = lv_scale_create(ui_SensorsChart);
    lv_scale_set_mode(ui_SensorsChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_SensorsChart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_SensorsChart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_SensorsChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_SensorsChart,
                                                                         LV_PART_MAIN) + lv_obj_get_style_border_width(ui_SensorsChart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_SensorsChart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_SensorsChart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_SensorsChart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_SensorsChart_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_SensorsChart_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_SensorsChart_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_SensorsChart_Xaxis, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_SensorsChart_Xaxis, 2 >= 1 ? 2 : 1);
    ui_SensorsChart_Yaxis1 = lv_scale_create(ui_SensorsChart);
    lv_scale_set_mode(ui_SensorsChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_SensorsChart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_SensorsChart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_SensorsChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_SensorsChart,
                                                                         LV_PART_MAIN) - lv_obj_get_style_border_width(ui_SensorsChart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_SensorsChart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_SensorsChart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_SensorsChart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_SensorsChart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_SensorsChart_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_SensorsChart_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_SensorsChart_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_SensorsChart_Yaxis2 = lv_scale_create(ui_SensorsChart);
    lv_scale_set_mode(ui_SensorsChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_SensorsChart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_SensorsChart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_SensorsChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_SensorsChart,
                                                                         LV_PART_MAIN) + lv_obj_get_style_border_width(ui_SensorsChart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_SensorsChart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_SensorsChart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_SensorsChart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_SensorsChart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_SensorsChart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_SensorsChart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_SensorsChart_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_SensorsChart_series_1 = lv_chart_add_series(ui_SensorsChart, lv_color_hex(0x00D96E),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_SensorsChart_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_SensorsChart, ui_SensorsChart_series_1, ui_SensorsChart_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_SensorsChart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_SensorsChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    uic_SystemTab = ui_SystemTab;
    uic_Status = ui_Status;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_SystemTab = NULL;
    ui_SystemTab = NULL;
    ui_StatusTab = NULL;
    uic_Status = NULL;
    ui_Status = NULL;
    ui_Wifi = NULL;
    ui_WifiStatus = NULL;
    ui_SSID = NULL;
    ui_IpAddress = NULL;
    ui_WebPage = NULL;
    ui_System = NULL;
    ui_CpuTemp = NULL;
    ui_CpuLoad = NULL;
    ui_RamUsage = NULL;
    ui_UpTime = NULL;
    ui_SensorsTab = NULL;
    ui_SensorsData = NULL;
    ui_SensorsChart = NULL;

}
