// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_SystemTab;
extern lv_obj_t * ui_StatusTab;
extern lv_obj_t * ui_Status;
extern lv_obj_t * ui_TimeDate;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_WifiStatus;
extern lv_obj_t * ui_SSID;
extern lv_obj_t * ui_IpAddress;
extern lv_obj_t * ui_WebPage;
extern lv_obj_t * ui_System;
extern lv_obj_t * ui_CpuTemp;
extern lv_obj_t * ui_CpuLoad;
extern lv_obj_t * ui_RamUsage;
extern lv_obj_t * ui_UpTime;
extern lv_obj_t * ui_SensorsTab;
extern lv_obj_t * ui_SensorsData;
extern lv_obj_t * ui_TemperatureContainer;
extern lv_obj_t * ui_TemperatureLable;
extern lv_obj_t * ui_TemperatureChart;
extern lv_obj_t * ui_TemperatureChart_Xaxis;
extern lv_obj_t * ui_TemperatureChart_Yaxis1;
extern lv_obj_t * ui_TemperatureChart_Yaxis2;
extern lv_obj_t * ui_HumidityContainer;
extern lv_obj_t * ui_HumidityLable;
extern lv_obj_t * ui_HumidityChart;
extern lv_obj_t * ui_HumidityChart_Xaxis;
extern lv_obj_t * ui_HumidityChart_Yaxis1;
extern lv_obj_t * ui_HumidityChart_Yaxis2;
extern lv_obj_t * ui_PressureContainer;
extern lv_obj_t * ui_PressureLable;
extern lv_obj_t * ui_PressureChart;
extern lv_obj_t * ui_PressureChart_Xaxis;
extern lv_obj_t * ui_PressureChart_Yaxis1;
extern lv_obj_t * ui_PressureChart_Yaxis2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SystemTab;
extern lv_obj_t * uic_Status;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

