// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_SystemTab;
extern lv_obj_t * ui_StatusTab;
extern lv_obj_t * ui_Status;
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_WifiStatus;
extern lv_obj_t * ui_SSID;
extern lv_obj_t * ui_IpAddress;
extern lv_obj_t * ui_WebPage;
extern lv_obj_t * ui_System;
extern lv_obj_t * ui_CpuTemp;
extern lv_obj_t * ui_CpuLoad;
extern lv_obj_t * ui_RamUsage;
extern lv_obj_t * ui_UpTime;
extern lv_obj_t * ui_SensorsTab;
extern lv_obj_t * ui_SensorsData;
extern lv_obj_t * ui_SensorsChart;
extern lv_obj_t * ui_SensorsChart_Xaxis;
extern lv_obj_t * ui_SensorsChart_Yaxis1;
extern lv_obj_t * ui_SensorsChart_Yaxis2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SystemTab;
extern lv_obj_t * uic_Status;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

